// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.accessTokenCreateStmt, err = db.PrepareContext(ctx, accessTokenCreate); err != nil {
		return nil, fmt.Errorf("error preparing query AccessTokenCreate: %w", err)
	}
	if q.accessTokenDeleteAllByUserIdStmt, err = db.PrepareContext(ctx, accessTokenDeleteAllByUserId); err != nil {
		return nil, fmt.Errorf("error preparing query AccessTokenDeleteAllByUserId: %w", err)
	}
	if q.accessTokenGetByIdStmt, err = db.PrepareContext(ctx, accessTokenGetById); err != nil {
		return nil, fmt.Errorf("error preparing query AccessTokenGetById: %w", err)
	}
	if q.accessTokenRefreshStmt, err = db.PrepareContext(ctx, accessTokenRefresh); err != nil {
		return nil, fmt.Errorf("error preparing query AccessTokenRefresh: %w", err)
	}
	if q.userCreateStmt, err = db.PrepareContext(ctx, userCreate); err != nil {
		return nil, fmt.Errorf("error preparing query UserCreate: %w", err)
	}
	if q.userDeleteStmt, err = db.PrepareContext(ctx, userDelete); err != nil {
		return nil, fmt.Errorf("error preparing query UserDelete: %w", err)
	}
	if q.userDisableStmt, err = db.PrepareContext(ctx, userDisable); err != nil {
		return nil, fmt.Errorf("error preparing query UserDisable: %w", err)
	}
	if q.userGetByIdStmt, err = db.PrepareContext(ctx, userGetById); err != nil {
		return nil, fmt.Errorf("error preparing query UserGetById: %w", err)
	}
	if q.userGetByUsernameStmt, err = db.PrepareContext(ctx, userGetByUsername); err != nil {
		return nil, fmt.Errorf("error preparing query UserGetByUsername: %w", err)
	}
	if q.userListStmt, err = db.PrepareContext(ctx, userList); err != nil {
		return nil, fmt.Errorf("error preparing query UserList: %w", err)
	}
	if q.userListCountStmt, err = db.PrepareContext(ctx, userListCount); err != nil {
		return nil, fmt.Errorf("error preparing query UserListCount: %w", err)
	}
	if q.userUpdateInfoStmt, err = db.PrepareContext(ctx, userUpdateInfo); err != nil {
		return nil, fmt.Errorf("error preparing query UserUpdateInfo: %w", err)
	}
	if q.userUpdatePasswordStmt, err = db.PrepareContext(ctx, userUpdatePassword); err != nil {
		return nil, fmt.Errorf("error preparing query UserUpdatePassword: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.accessTokenCreateStmt != nil {
		if cerr := q.accessTokenCreateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing accessTokenCreateStmt: %w", cerr)
		}
	}
	if q.accessTokenDeleteAllByUserIdStmt != nil {
		if cerr := q.accessTokenDeleteAllByUserIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing accessTokenDeleteAllByUserIdStmt: %w", cerr)
		}
	}
	if q.accessTokenGetByIdStmt != nil {
		if cerr := q.accessTokenGetByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing accessTokenGetByIdStmt: %w", cerr)
		}
	}
	if q.accessTokenRefreshStmt != nil {
		if cerr := q.accessTokenRefreshStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing accessTokenRefreshStmt: %w", cerr)
		}
	}
	if q.userCreateStmt != nil {
		if cerr := q.userCreateStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userCreateStmt: %w", cerr)
		}
	}
	if q.userDeleteStmt != nil {
		if cerr := q.userDeleteStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userDeleteStmt: %w", cerr)
		}
	}
	if q.userDisableStmt != nil {
		if cerr := q.userDisableStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userDisableStmt: %w", cerr)
		}
	}
	if q.userGetByIdStmt != nil {
		if cerr := q.userGetByIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userGetByIdStmt: %w", cerr)
		}
	}
	if q.userGetByUsernameStmt != nil {
		if cerr := q.userGetByUsernameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userGetByUsernameStmt: %w", cerr)
		}
	}
	if q.userListStmt != nil {
		if cerr := q.userListStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userListStmt: %w", cerr)
		}
	}
	if q.userListCountStmt != nil {
		if cerr := q.userListCountStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userListCountStmt: %w", cerr)
		}
	}
	if q.userUpdateInfoStmt != nil {
		if cerr := q.userUpdateInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userUpdateInfoStmt: %w", cerr)
		}
	}
	if q.userUpdatePasswordStmt != nil {
		if cerr := q.userUpdatePasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userUpdatePasswordStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                               DBTX
	tx                               *sql.Tx
	accessTokenCreateStmt            *sql.Stmt
	accessTokenDeleteAllByUserIdStmt *sql.Stmt
	accessTokenGetByIdStmt           *sql.Stmt
	accessTokenRefreshStmt           *sql.Stmt
	userCreateStmt                   *sql.Stmt
	userDeleteStmt                   *sql.Stmt
	userDisableStmt                  *sql.Stmt
	userGetByIdStmt                  *sql.Stmt
	userGetByUsernameStmt            *sql.Stmt
	userListStmt                     *sql.Stmt
	userListCountStmt                *sql.Stmt
	userUpdateInfoStmt               *sql.Stmt
	userUpdatePasswordStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                               tx,
		tx:                               tx,
		accessTokenCreateStmt:            q.accessTokenCreateStmt,
		accessTokenDeleteAllByUserIdStmt: q.accessTokenDeleteAllByUserIdStmt,
		accessTokenGetByIdStmt:           q.accessTokenGetByIdStmt,
		accessTokenRefreshStmt:           q.accessTokenRefreshStmt,
		userCreateStmt:                   q.userCreateStmt,
		userDeleteStmt:                   q.userDeleteStmt,
		userDisableStmt:                  q.userDisableStmt,
		userGetByIdStmt:                  q.userGetByIdStmt,
		userGetByUsernameStmt:            q.userGetByUsernameStmt,
		userListStmt:                     q.userListStmt,
		userListCountStmt:                q.userListCountStmt,
		userUpdateInfoStmt:               q.userUpdateInfoStmt,
		userUpdatePasswordStmt:           q.userUpdatePasswordStmt,
	}
}
