// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: example.sql

package model

import (
	"context"
)

const getOne = `-- name: GetOne :one
select 1
`

func (q *Queries) GetOne(ctx context.Context) (int64, error) {
	row := q.queryRow(ctx, q.getOneStmt, getOne)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
