// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"database/sql"
	"time"
)

type User struct {
	Id        string         `db:"id" json:"id"`
	CreatedAt time.Time      `db:"created_at" json:"createdAt"`
	UpdatedAt time.Time      `db:"updated_at" json:"updatedAt"`
	DeletedAt *time.Time     `db:"deleted_at" json:"deletedAt"`
	Nickname  sql.NullString `db:"nickname" json:"nickname"`
	Avatar    sql.NullString `db:"avatar" json:"avatar"`
	Brief     sql.NullString `db:"brief" json:"brief"`
	Username  string         `db:"username" json:"username"`
	Password  string         `db:"password" json:"password"`
	Salt      string         `db:"salt" json:"salt"`
	Disabled  bool           `db:"disabled" json:"disabled"`
}
