/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * Go Template API - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'health.get': ['GET', '/api/v1/health'],
  'user.changePassword': ['POST', '/api/v1/user/change-password'],
  'user.info': ['GET', '/api/v1/user/info'],
  'user.infoUpdate': ['POST', '/api/v1/user/info-update'],
  'user.list': ['GET', '/api/v1/user/list'],
  'user.signin': ['POST', '/api/v1/user/signin'],
  'user.signup': ['POST', '/api/v1/user/signup']
};
