/* tslint:disable */
/* eslint-disable */
/**
 * Go Template API - version 1.0.0
 *
 *
 *
 * OpenAPI version: 3.1.0
 *
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
import type { Alova, AlovaMethodCreateConfig, AlovaGenerics, Method } from 'alova';
import type { $$userConfigMap, alovaInstance } from './index';
import type apiDefinitions from './apiDefinitions';

type CollapsedAlova = typeof alovaInstance;
type UserMethodConfigMap = typeof $$userConfigMap;

type Alova2MethodConfig<Responded> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Omit<
        AlovaMethodCreateConfig<
          AlovaGenerics<Responded, any, RequestConfig, Response, ResponseHeader, L1Cache, L2Cache, SE>,
          any,
          Responded
        >,
        'params'
      >
    : never;

// Extract the return type of transform function that define in $$userConfigMap, if it not exists, use the default type.
type ExtractUserDefinedTransformed<
  DefinitionKey extends keyof typeof apiDefinitions,
  Default
> = DefinitionKey extends keyof UserMethodConfigMap
  ? UserMethodConfigMap[DefinitionKey]['transform'] extends (...args: any[]) => any
    ? Awaited<ReturnType<UserMethodConfigMap[DefinitionKey]['transform']>>
    : Default
  : Default;
type Alova2Method<
  Responded,
  DefinitionKey extends keyof typeof apiDefinitions,
  CurrentConfig extends Alova2MethodConfig<any>
> =
  CollapsedAlova extends Alova<
    AlovaGenerics<
      any,
      any,
      infer RequestConfig,
      infer Response,
      infer ResponseHeader,
      infer L1Cache,
      infer L2Cache,
      infer SE
    >
  >
    ? Method<
        AlovaGenerics<
          CurrentConfig extends undefined
            ? ExtractUserDefinedTransformed<DefinitionKey, Responded>
            : CurrentConfig['transform'] extends (...args: any[]) => any
              ? Awaited<ReturnType<CurrentConfig['transform']>>
              : ExtractUserDefinedTransformed<DefinitionKey, Responded>,
          any,
          RequestConfig,
          Response,
          ResponseHeader,
          L1Cache,
          L2Cache,
          SE
        >
      >
    : never;

export interface UserChangePasswordRequest {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  password: string;
  passwordNew: string;
}
export interface UserInfoUpdateRequest {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  avatar?: string;
  brief?: string;
  nickname?: string;
}
export interface UserSigninRequest {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  password: string;
  username: string;
}
export interface UserSignupRequest {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  avatar?: string;
  brief?: string;
  nickname: string;
  password: string;
  username: string;
}
export interface MessageResponseBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  /**
   * 提示信息
   */
  message: string;
}
export interface UserDTO {
  avatar?: string;
  brief?: string;
  createdAt: string;
  deletedAt?: string;
  disabled: boolean;
  id: string;
  nickname?: string;
  updatedAt: string;
  username: string;
}
export interface UserInfoResponse {
  user: UserDTO;
}
export interface InfoOutputBody {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  item: UserInfoResponse;
}
export interface UserResponse {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  item: UserDTO;
}
export interface UserListResponse {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  items: UserDTO[] | null;
  page: number;
  size: number;
  total: number;
}
export interface AuthResponse {
  /**
   * A URL to the JSON Schema for this object.
   */
  $schema?: string;
  message: string;
  token: string;
}
declare global {
  interface Apis {
    health: {
      /**
       * ---
       *
       * [GET] 健康探测
       *
       * **path:** /api/v1/health
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // 提示信息
       *   message: string
       * }
       * ```
       */
      get<Config extends Alova2MethodConfig<MessageResponseBody>>(
        config?: Config
      ): Alova2Method<MessageResponseBody, 'health.get', Config>;
    };
    user: {
      /**
       * ---
       *
       * [POST] 修改密码
       *
       * **path:** /api/v1/user/change-password
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   password: string
       *   passwordNew: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = Record<string, string>
       * ```
       */
      changePassword<
        Config extends Alova2MethodConfig<Record<string, string>> & {
          data: UserChangePasswordRequest;
        }
      >(
        config: Config
      ): Alova2Method<Record<string, string>, 'user.changePassword', Config>;
      /**
       * ---
       *
       * [GET] 获取当前用户信息
       *
       * **path:** /api/v1/user/info
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   item: {
       *     user: {
       *       avatar?: string
       *       brief?: string
       *       createdAt: string
       *       deletedAt?: string
       *       disabled: boolean
       *       id: string
       *       nickname?: string
       *       updatedAt: string
       *       username: string
       *     }
       *   }
       * }
       * ```
       */
      info<Config extends Alova2MethodConfig<InfoOutputBody>>(
        config?: Config
      ): Alova2Method<InfoOutputBody, 'user.info', Config>;
      /**
       * ---
       *
       * [POST] 更新当前用户信息
       *
       * **path:** /api/v1/user/info-update
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   avatar?: string
       *   brief?: string
       *   nickname?: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   item: {
       *     avatar?: string
       *     brief?: string
       *     createdAt: string
       *     deletedAt?: string
       *     disabled: boolean
       *     id: string
       *     nickname?: string
       *     updatedAt: string
       *     username: string
       *   }
       * }
       * ```
       */
      infoUpdate<
        Config extends Alova2MethodConfig<UserResponse> & {
          data: UserInfoUpdateRequest;
        }
      >(
        config: Config
      ): Alova2Method<UserResponse, 'user.infoUpdate', Config>;
      /**
       * ---
       *
       * [GET] 用户列表
       *
       * **path:** /api/v1/user/list
       *
       * ---
       *
       * **Query Parameters**
       * ```ts
       * type QueryParameters = {
       *   page?: number
       *   size?: number
       *   keyword?: string
       *   includeDisabled?: boolean
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   // [params1] start
       *   // [items] start
       *   // [items] end
       *   // [params1] end
       *   items: Array<{
       *     avatar?: string
       *     brief?: string
       *     createdAt: string
       *     deletedAt?: string
       *     disabled: boolean
       *     id: string
       *     nickname?: string
       *     updatedAt: string
       *     username: string
       *   }> | null
       *   page: number
       *   size: number
       *   total: number
       * }
       * ```
       */
      list<
        Config extends Alova2MethodConfig<UserListResponse> & {
          params: {
            page?: number;
            size?: number;
            keyword?: string;
            includeDisabled?: boolean;
          };
        }
      >(
        config: Config
      ): Alova2Method<UserListResponse, 'user.list', Config>;
      /**
       * ---
       *
       * [POST] 用户登录
       *
       * **path:** /api/v1/user/signin
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   password: string
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   message: string
       *   token: string
       * }
       * ```
       */
      signin<
        Config extends Alova2MethodConfig<AuthResponse> & {
          data: UserSigninRequest;
        }
      >(
        config: Config
      ): Alova2Method<AuthResponse, 'user.signin', Config>;
      /**
       * ---
       *
       * [POST] 用户注册
       *
       * **path:** /api/v1/user/signup
       *
       * ---
       *
       * **RequestBody**
       * ```ts
       * type RequestBody = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   avatar?: string
       *   brief?: string
       *   nickname: string
       *   password: string
       *   username: string
       * }
       * ```
       *
       * ---
       *
       * **Response**
       * ```ts
       * type Response = {
       *   // A URL to the JSON Schema for this object.
       *   $schema?: string
       *   item: {
       *     avatar?: string
       *     brief?: string
       *     createdAt: string
       *     deletedAt?: string
       *     disabled: boolean
       *     id: string
       *     nickname?: string
       *     updatedAt: string
       *     username: string
       *   }
       * }
       * ```
       */
      signup<
        Config extends Alova2MethodConfig<UserResponse> & {
          data: UserSignupRequest;
        }
      >(
        config: Config
      ): Alova2Method<UserResponse, 'user.signup', Config>;
    };
  }

  var Apis: Apis;
}
